apiVersion: v1
kind: Pod
metadata:
  name: job1-migr
spec:
  containers:
  - args:
    - bidirectional_rnn_imag.py
    - /root/job1.csv
    - job1
    command:
    - python
    image: wyan16/birnn
    name: birnn-test-epoch
    volumeMounts:
    - mountPath: /root/
      name: task-pv-storage
  nodeName: node-3.k8stest2.shield-pg0.utah.cloudlab.us
  restartPolicy: Never
  volumes:
  - name: task-pv-storage
    persistentVolumeClaim:
      claimName: pvc1-nfs
