kind: Pod
apiVersion: v1
metadata:
  name: job2-birnn
spec:
  restartPolicy: Never
  volumes:
  - name: task-pv-storage
    persistentVolumeClaim:
      claimName: pvc1-nfs
  containers:
    - name: birnn-test-epoch
      image: wyan16/birnn
      command: ["python"]
      args: ["bidirectional_rnn_imag.py","/root/torch/job2-birnn.csv","job2-birnn"]
      volumeMounts:
      - mountPath: "/root/torch"
        name: task-pv-storage

